### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by bsipocz** [NASA-NAVO/navo-workshop#63]
These are the follow-up TODO items from #62:

- [x] add cron  #65 
- [x] add multi OS testing #71
- [x] add multi-version testing, including pyvo-dev 
- [x] turn sphinx warnings about  code exceptions into proper failures
  - [x] turn sphinx-warnings into exceptions (nitpicky) #65
  - [x] turn cell execution errors into exceptions, separate this out from the sphinx build to a test run #71

**Comment by bsipocz** [comment]
I think everything is addressed here by #71
